detik = float(input("Masukan nilai detik =" ))
menit = float(detik/60)
jam = float(detik/3600)
print(detik, "detik dirubah ke menit=",menit,"menit")
print(detik, "detik dirubah ke jam=",jam,"jam")